# Generated by Django 5.2.17 on 2026-08-14 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessioneTerminale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aperta_il', models.DateTimeField(auto_now_add=True)),
                ('chiusa_il', models.DateTimeField(blank=True, null=True)),
                ('errore', models.TextField(blank=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessioni_terminale', to='hub.target')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-aperta_il'],
            },
        ),
    ]
