server {
    listen 127.0.0.1:8452 ssl;
    server_name 127.0.0.1;

    ssl_certificate     /etc/letsencrypt/live/aigate.fbosolution.it/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aigate.fbosolution.it/privkey.pem;

    location /api/internal/ {
        allow 127.0.0.1;
        deny all;
        proxy_pass http://unix:/run/fboaigate/daphne.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }
}
