# Generated by Django 5.2.17 on 2026-10-06 06:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('note', models.TextField(blank=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'clienti',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Postazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Es. "Segreteria", "PC magazzino".', max_length=100)),
                ('rustdesk_id', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]{6,16}$', 'ID RustDesk non valido.')], verbose_name='ID RustDesk')),
                ('sistema', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux')], default='windows', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('ultima_connessione', models.DateTimeField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postazioni', to='assistenza.cliente')),
            ],
            options={
                'verbose_name_plural': 'postazioni',
                'ordering': ['cliente__nome', 'nome'],
            },
        ),
    ]
