# Generated by Django 5.2.17 on 2026-10-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postazione',
            name='ultimo_online',
            field=models.DateTimeField(blank=True, help_text='Ultima volta visto online dalla lista.', null=True),
        ),
    ]
