# Generated by Django 5.2.17 on 2026-08-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Es. "NUC casa", "VPS produzione".', max_length=100, unique=True)),
                ('vpn_ip', models.GenericIPAddressField(help_text="Indirizzo assegnato sull'hub WireGuard di FBOAIGate (es. 10.20.0.2).", protocol='IPv4', unique=True)),
                ('wireguard_public_key', models.CharField(blank=True, max_length=64)),
                ('ssh_user', models.CharField(max_length=100)),
                ('online', models.BooleanField(default=False)),
                ('ultimo_contatto', models.DateTimeField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
